# Generated by Django 4.0.8 on 2023-02-05 01:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import schedul.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=schedul.models.nym_gen, max_length=256)),
                ('parties', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSpan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='schedul.event')),
            ],
            options={
                'ordering': ['begin'],
            },
        ),
        migrations.CreateModel(
            name='EmailToken',
            fields=[
                ('key', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('expires', models.DateTimeField(editable=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedul.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DispatchLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('occurrence', models.CharField(choices=[('UPDATE', 'Update'), ('NOTIFY', 'Notify'), ('VIEW', 'View')], max_length=32)),
                ('effector', models.CharField(max_length=254)),
                ('slots', models.CharField(max_length=2048)),
                ('data', models.CharField(default='{}', max_length=512)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_log', to='schedul.event')),
            ],
        ),
    ]
