# Generated by Django 3.2.9 on 2021-12-25 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedul', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timespan',
            options={'ordering': ['begin']},
        ),
    ]
