# Generated by Django 3.2.9 on 2022-01-11 21:36

from django.db import migrations, models
import schedul.models


class Migration(migrations.Migration):

    dependencies = [
        ('schedul', '0002_alter_timespan_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default=schedul.models.nym_gen, max_length=256),
        ),
    ]
