# Generated by Django 3.2.9 on 2022-04-05 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import schedul.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedul', '0004_auto_20220204_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailToken',
            fields=[
                ('key', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('expires', models.DateTimeField(default=schedul.models.five_days_hence, editable=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedul.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
