
services:
  web:
    container_name: caldc
    image: caldi
    build:
      context: .
      dockerfile: compose/local/Dockerfile
    env_file: ./compose/local/.env.dj
    ports:
      - ${HOST_PORT:-8000}:8000
    #volumes:
    #logging:

