
services:
  dj:
    container_name: caldc
    image: caldi
    build:
      context: .
      dockerfile: compose/local/Dockerfile
    env_file: ./compose/local/dj.env
    ports:
      - ${HOST_PORT:-8000}:8000
    volumes:
      - ./db.sqlite3:/code/db.sqlite3

networks:
  default:
    name: cald_loc

