FROM python:3-alpine
#RUN apk update && apk add libpq

ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1

RUN addgroup -S app && adduser -G app -S app
USER app
WORKDIR /home/app
COPY --chown=app:app . .

# dbg
RUN set -ex && ls -lhtrA \
    && whoami && pwd \
    && python --version && cat /etc/os-release

RUN set -ex && python -m venv venv && . venv/bin/activate \
    && pip install -r requirements/stage.txt \
    && ./manage.py migrate \
    && ./manage.py collectstatic

ENV VIRTUAL_ENV=/home/app/venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

EXPOSE 8000
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "config.wsgi:application"]
#CMD ["./manage.py", "runserver", "0.0.0.0:8000"]
