name: CI
on:
  push
env:
  # X:
  ENV_PATH: 'config/ci.env'
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # X: %volatile
        python-version: [3.8, 3.9, "3.10"]
        #python-version: ["3.10"]
        #python-version: ["3.6", 3.7]
    steps: 
      - name: checkout
        uses: actions/checkout@v2
      - name: setup py ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with: 
          python-version: ${{ matrix.python-version }}
      - name: deps
        run: pip install --upgrade pip && pip install -r requirements/base.txt
        #run: pip install -r requirements/base.txt
      - name: db
        run: python manage.py makemigrations && python manage.py migrate
        #run: python manage.py migrate
      - name: test
        run: python manage.py test

